version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: uedit_postgres
    restart: always
    environment:
      POSTGRES_USER: uedit
      POSTGRES_PASSWORD: uedit123
      POSTGRES_DB: ueditdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: project-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000
    container_name: project-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
