services:
  backend:
    build: ./backend
    container_name: project-backend
    ports:
      - "5000:5000"
    command: ["dotnet", "UEdit.Backend.dll", "--urls=http://0.0.0.0:5000"]

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:5000
    container_name: project-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
